plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    runtimeOnly "org.anarres:jcpp:1.4.14"
    implementation "io.github.douira:glsl-transformer:3.0.0-pre3"

    compileOnly "dev.engine-room.flywheel:flywheel-fabric-26.1:${flywheel_version}"
    //compileOnly "net.createmod.ponder:ponder-fabric:${ponder_version}+mc${minecraft_version}"

    compileOnly "maven.modrinth:iris:${iris_version}-fabric"

    runtimeOnly "dev.engine-room.flywheel:flywheel-fabric-26.1:${flywheel_version}"
    runtimeOnly "dev.engine-room.vanillin:vanillin-fabric-26.1:${vanillin_version}"

    runtimeOnly "maven.modrinth:sodium:${sodium_version}-fabric"
    runtimeOnly "maven.modrinth:iris:${iris_version}-fabric"
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements', 'includeInternal', 'modCompileClasspath'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'fabric')
            }
        }
    }
}
