#include "colorwheel:internal/uniform/frame.glsl"
#include "colorwheel:internal/uniform/pass.glsl"
#include "colorwheel:internal/uniform/level.glsl"
#include "colorwheel:internal/uniform/player.glsl"
#include "colorwheel:internal/uniform/fog.glsl"
#include "colorwheel:internal/uniform/options.glsl"
