modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "colorwheel"
version = "${version}"
displayName = "Colorwheel"
authors = "djefrey"
description = '''
Allows you to use Iris Shaders with Flywheel
'''
logoFile = "logo.png"

[[dependencies.colorwheel]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.colorwheel]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.colorwheel]]
modId = "flywheel"
type = "optional"
versionRange = "[1.0.0,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.colorwheel]]
modId = "iris"
type = "required"
versionRange = "[1.8.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.colorwheel]]
modId = "colorwheel_patcher"
type = "optional"
versionRange = "[0.2.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.colorwheel]]
modId = "irisflw"
type = "incompatible"
versionRange = "*"
side = "CLIENT"
reason = "Mixin conflict with Iris Flywheel Compat"

[[mixins]]
config = "colorwheel.mixins.json"

[[mixins]]
config = "colorwheel.neoforge.mixins.json"
