modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
issueTrackerURL = "https://github.com/djefrey/Colorwheel/issues"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "https://djefrey.github.io/colorwheel/"
authors = "djefrey"
description = '''
Allows you to use Iris Shaders with Flywheel
'''
logoFile="${mod_id}.png"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "flywheel"
type = "optional"
versionRange = "[1.0.0,2.0.0)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "iris"
type = "required"
versionRange = "[1.10.7,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "colorwheel_patcher"
type = "optional"
versionRange = "[1.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "sable"
type = "optional"
versionRange = "[1.1.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "irisflw"
type = "incompatible"
versionRange = "*"
side = "CLIENT"
reason = "Mixin conflict with Iris Flywheel Compat"

[[mixins]]
config = "colorwheel.mixins.json"

[[mixins]]
config = "colorwheel.neoforge.mixins.json"
