modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "colorwheel"
version = "${version}"
displayName = "Colorwheel"
authors = "djefrey"
description = '''
Allows you to use Iris Shaders with Flywheel
'''
logoFile = "logo.png"

[[dependencies.colorwheel]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.colorwheel]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.colorwheel]]
modId = "flywheel"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.colorwheel]]
modId = "iris"
mandatory = true
versionRange = "[1.8.0,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "colorwheel.mixins.iris.json"

[[mixins]]
config = "colorwheel.mixins.flw.json"

[[mixins]]
config = "colorwheel.mixins.mc.json"
